package com.webcommander.plugin.jssor_slider.constant

class DomainConstant {
    public static CAPTION_TYPE = [
        TITLE: "title",
        DESCRIPTION: "description",
        BUTTON: "button"
    ]

    public static NAVIGATION_VISIBILITY = [
        always: 2,
        mouse_over: 1,
        never: 0
    ]

    public static CAPTION_TRANSITIONS = [
        'Move': [
            'Left': 'L',
            'Right': 'R',
            'Top': 'T',
            'Bottom': 'B'
        ],
        'Fade': [
            'FADE': 'Fade'
        ],
        'ZOOM': [
            'Zoom P80': 'ZM|P80',
            'Zoom F|2': 'ZMF|2'
        ]
    ]
    
    /*public static CAPTION_TRANSITIONS = [
        'Move': [
            'L': 'L',
            'R': 'R',
            'T': 'T',
            'B': 'B',
            'TL': 'TL',
            'TR': 'TR',
            'BL': 'BL',
            'BR': 'BR',
            'Move|IB': null,
            'L|IB': 'L|IB',
            'R|IB': 'R|IB',
            'T|IB': 'T|IB',
            'B|IB': 'B|IB',
            'TL|IB': 'TL|IB',
            'TR|IB': 'TR|IB',
            'BL|IB': 'BL|IB',
            'BR|IB': 'BR|IB',
            'Move|IE': null,
            'L|IE': 'L|IE',
            'R|IE': 'R|IE',
            'T|IE': 'T|IE',
            'B|IE': 'B|IE',
            'TL|IE': 'TL|IE',
            'TR|IE': 'TR|IE',
            'BL|IE': 'BL|IE',
            'BR|IE': 'BR|IE'
        ],
        'Move|EP': [
            'L|EP': 'L|EP',
            'R|EP': 'R|EP',
            'T|EP': 'T|EP',
            'B|EP': 'B|EP',
            'TL|EP': 'TL|EP',
            'TR|EP': 'TR|EP',
            'BL|EP': 'BL|EP',
            'BR|EP': 'BR|EP'
        ],
        'Move with Rotate': [
            'L*': 'L*',
            'R*': 'R*',
            'T*': 'T*',
            'B*': 'B*',
            'TL*': 'TL*',
            'TR*': 'TR*',
            'BL*': 'BL*',
            'BR*': 'BR*'
        ],
        'Move with Rotate IE': [
            'L*IE': 'L*IE',
            'R*IE': 'R*IE',
            'T*IE': 'T*IE',
            'B*IE': 'B*IE',
            'TL*IE': 'TL*IE',
            'TR*IE': 'TR*IE',
            'BL*IE': 'BL*IE',
            'BR*IE': 'BR*IE'
        ],
        'Move with Rotate IB': [
            'L*IB': 'L*IB',
            'R*IB': 'R*IB',
            'T*IB': 'T*IB',
            'B*IB': 'B*IB',
            'TL*IB': 'TL*IB',
            'TR*IB': 'TR*IB',
            'BL*IB': 'BL*IB',
            'BR*IB': 'BR*IB'
        ],
        'Move - Rotate IB': [
            'L-*IB': 'L-*IB',
            'R-*IB': 'R-*IB',
            'T-*IB': 'T-*IB',
            'B-*IB': 'B-*IB',
            'TL-*IB': 'TL-*IB',
            'TR-*IB': 'TR-*IB',
            'BL-*IB': 'BL-*IB',
            'BR-*IB': 'BR-*IB'
        ],
        'Move with Rotate IW': [
            'L*IW': 'L*IW',
            'R*IW': 'R*IW',
            'T*IW': 'T*IW',
            'B*IW': 'B*IW',
            'TL*IW': 'TL*IW',
            'TR*IW': 'TR*IW',
            'BL*IW': 'BL*IW',
            'BR*IW': 'BR*IW'
        ],
        'Move IE with Rotate IE': [
            'L|IE*IE': 'L|IE*IE',
            'R|IE*IE': 'R|IE*IE',
            'T|IE*IE': 'T|IE*IE',
            'B|IE*IE': 'B|IE*IE',
            'TL|IE*IE': 'TL|IE*IE',
            'TR|IE*IE': 'TR|IE*IE',
            'BL|IE*IE': 'BL|IE*IE',
            'BR|IE*IE': 'BR|IE*IE'
        ],
        'Clip': [
            'CLIP': 'CLIP',
            'CLIP|LR': 'CLIP|LR',
            'CLIP|TB': 'CLIP|TB',
            'CLIP|L': 'CLIP|L',
            'CLIP|R': 'CLIP|R',
            'CLIP|T': 'CLIP|T',
            'CLIP|B': 'CLIP|B',
        ],
        'MClip': [
            'MCLIP|L': 'MCLIP|L',
            'MCLIP|R': 'MCLIP|R',
            'MCLIP|T': 'MCLIP|T',
            'MCLIP|B': 'MCLIP|B'
        ],
        'Zoom': [
            'ZM': 'ZM',
            'ZM|P30': 'ZM|P30',
            'ZM|P50': 'ZM|P50',
            'ZM|P70': 'ZM|P70',
            'ZM|P80': 'ZM|P80',
            'ZMF|2': 'ZMF|2',
            'ZMF|3': 'ZMF|3',
            'ZMF|4': 'ZMF|4',
            'ZMF|5': 'ZMF|5',
            'ZMF|10': 'ZMF|10',
            'ZML|L': 'ZML|L',
            'ZML|R': 'ZML|R',
            'ZML|T': 'ZML|T',
            'ZML|B': 'ZML|B',
            'ZML|TL': 'ZML|TL',
            'ZML|TR': 'ZML|TR',
            'ZML|BL': 'ZML|BL',
            'ZML|BR': 'ZML|BR',
            'ZML|IE|L': 'ZML|IE|L',
            'ZML|IE|R': 'ZML|IE|R',
            'ZML|IE|T': 'ZML|IE|T',
            'ZML|IE|B': 'ZML|IE|B',
            'ZML|IE|TL': 'ZML|IE|TL',
            'ZML|IE|TR': 'ZML|IE|TR',
            'ZML|IE|BL': 'ZML|IE|BL',
            'ZML|IE|BR': 'ZML|IE|BR',
            'ZMS|L': 'ZMS|L',
            'ZMS|R': 'ZMS|R',
            'ZMS|T': 'ZMS|T',
            'ZMS|B': 'ZMS|B',
            'ZMS|TL': 'ZMS|TL',
            'ZMS|TR': 'ZMS|TR',
            'ZMS|BL': 'ZMS|BL',
            'ZMS|BR': 'ZMS|BR'
        ],
        'Zoom with Jump': [
            'ZM*JDN|LT': 'ZM*JDN|LT',
            'ZM*JDN|LB': 'ZM*JDN|LB',
            'ZM*JDN|RT': 'ZM*JDN|RT',
            'ZM*JDN|RB': 'ZM*JDN|RB',
            'ZM*JDN|TL': 'ZM*JDN|TL',
            'ZM*JDN|TR': 'ZM*JDN|TR',
            'ZM*JDN|BL': 'ZM*JDN|BL',
            'ZM*JDN|BR': 'ZM*JDN|BR',
            'ZM*JUP|LT': 'ZM*JUP|LT',
            'ZM*JUP|LB': 'ZM*JUP|LB',
            'ZM*JUP|RT': 'ZM*JUP|RT',
            'ZM*JUP|RB': 'ZM*JUP|RB',
            'ZM*JUP|TL': 'ZM*JUP|TL',
            'ZM*JUP|TR': 'ZM*JUP|TR',
            'ZM*JUP|BL': 'ZM*JUP|BL',
            'ZM*JUP|BR': 'ZM*JUP|BR',
            'ZM*JDN|LB*': 'ZM*JDN|LB*',
            'ZM*JDN|RB*': 'ZM*JDN|RB*',
            'ZM*JDN1|L': 'ZM*JDN1|L',
            'ZM*JDN1|R': 'ZM*JDN1|R',
            'ZM*JDN1|T': 'ZM*JDN1|T',
            'ZM*JDN1|B': 'ZM*JDN1|B',
            'ZM*JUP1|L': 'ZM*JUP1|L',
            'ZM*JUP1|R': 'ZM*JUP1|R',
            'ZM*JUP1|T': 'ZM*JUP1|T',
            'ZM*JUP1|B': 'ZM*JUP1|B',
            'Zoom with Wave': null,
            'ZM*WVC|LT': 'ZM*WVC|LT',
            'ZM*WVC|LB': 'ZM*WVC|LB',
            'ZM*WVC|RT': 'ZM*WVC|RT',
            'ZM*WVC|RB': 'ZM*WVC|RB',
            'ZM*WVC|TL': 'ZM*WVC|TL',
            'ZM*WVC|TR': 'ZM*WVC|TR',
            'ZM*WVC|BL': 'ZM*WVC|BL',
            'ZM*WVC|BR': 'ZM*WVC|BR',
            'ZM*WVR|LT': 'ZM*WVR|LT',
            'ZM*WVR|LB': 'ZM*WVR|LB',
            'ZM*WVR|RT': 'ZM*WVR|RT',
            'ZM*WVR|RB': 'ZM*WVR|RB',
            'ZM*WVR|TL': 'ZM*WVR|TL',
            'ZM*WVR|TR': 'ZM*WVR|TR',
            'ZM*WVR|BL': 'ZM*WVR|BL',
            'ZM*WVR|BR': 'ZM*WVR|BR'
        ],
        'Zoom with Wave with Jump 1': [
            'ZM*WV*J1|LT': 'ZM*WV*J1|LT',
            'ZM*WV*J1|LB': 'ZM*WV*J1|LB',
            'ZM*WV*J1|RT': 'ZM*WV*J1|RT',
            'ZM*WV*J1|RB': 'ZM*WV*J1|RB',
            'ZM*WV*J1|TL': 'ZM*WV*J1|TL',
            'ZM*WV*J1|TR': 'ZM*WV*J1|TR',
            'ZM*WV*J1|BL': 'ZM*WV*J1|BL',
            'ZM*WV*J1|BR': 'ZM*WV*J1|BR'
        ],
        'Zoom with Wave with Jump 2': [
            'ZM*WV*J2|LT': 'ZM*WV*J2|LT',
            'ZM*WV*J2|LB': 'ZM*WV*J2|LB',
            'ZM*WV*J2|RT': 'ZM*WV*J2|RT',
            'ZM*WV*J2|RB': 'ZM*WV*J2|RB',
            'ZM*WV*J2|TL': 'ZM*WV*J2|TL',
            'ZM*WV*J2|TR': 'ZM*WV*J2|TR',
            'ZM*WV*J2|BL': 'ZM*WV*J2|BL',
            'ZM*WV*J2|BR': 'ZM*WV*J2|BR',
        ],
        'Zoom with Wave with Jump 3': [
            'ZM*WV*J3|LT': 'ZM*WV*J3|LT',
            'ZM*WV*J3|LB': 'ZM*WV*J3|LB',
            'ZM*WV*J3|RT': 'ZM*WV*J3|RT',
            'ZM*WV*J3|RB': 'ZM*WV*J3|RB',
            'ZM*WV*J3|TL': 'ZM*WV*J3|TL',
            'ZM*WV*J3|TR': 'ZM*WV*J3|TR',
            'ZM*WV*J3|BL': 'ZM*WV*J3|BL',
            'ZM*WV*J3|BR': 'ZM*WV*J3|BR'
        ],
        'Rotate': [
            'RTT': 'RTT',
            'RTT|90': 'RTT|90',
            'RTT|360': 'RTT|360',
            'RTT|0': 'RTT|0',
            'RTT|2': 'RTT|2',
            'RTT|3': 'RTT|3',
            'RTT|4': 'RTT|4',
            'RTT|5': 'RTT|5',
            'RTT|10': 'RTT|10',
            'RTTL|L': 'RTTL|L',
            'RTTL|R': 'RTTL|R',
            'RTTL|T': 'RTTL|T',
            'RTTL|B': 'RTTL|B',
            'RTTL|TL': 'RTTL|TL',
            'RTTL|TR': 'RTTL|TR',
            'RTTL|BL': 'RTTL|BL',
            'RTTL|BR': 'RTTL|BR',
            'RTTS|L': 'RTTS|L',
            'RTTS|R': 'RTTS|R',
            'RTTS|T': 'RTTS|T',
            'RTTS|B': 'RTTS|B',
            'RTTS|TL': 'RTTS|TL',
            'RTTS|TR': 'RTTS|TR',
            'RTTS|BL': 'RTTS|BL',
            'RTTS|BR': 'RTTS|BR'
        ],
        'Rotate with Jump': [
            'RTT*JDN|L': 'RTT*JDN|L',
            'RTT*JDN|R': 'RTT*JDN|R',
            'RTT*JDN|T': 'RTT*JDN|T',
            'RTT*JDN|B': 'RTT*JDN|B',
            'RTT*JUP|L': 'RTT*JUP|L',
            'RTT*JUP|R': 'RTT*JUP|R',
            'RTT*JUP|T': 'RTT*JUP|T',
            'RTT*JUP|B': 'RTT*JUP|B',
            'RTT*JDN|LT': 'RTT*JDN|LT',
            'RTT*JDN|LB': 'RTT*JDN|LB',
            'RTT*JDN|RT': 'RTT*JDN|RT',
            'RTT*JDN|RB': 'RTT*JDN|RB',
            'RTT*JDN|TL': 'RTT*JDN|TL',
            'RTT*JDN|TR': 'RTT*JDN|TR',
            'RTT*JDN|BL': 'RTT*JDN|BL',
            'RTT*JDN|BR': 'RTT*JDN|BR',
            'RTT*JUP|LT': 'RTT*JUP|LT',
            'RTT*JUP|LB': 'RTT*JUP|LB',
            'RTT*JUP|RT': 'RTT*JUP|RT',
            'RTT*JUP|RB': 'RTT*JUP|RB',
            'RTT*JUP|TL': 'RTT*JUP|TL',
            'RTT*JUP|TR': 'RTT*JUP|TR',
            'RTT*JUP|BL': 'RTT*JUP|BL',
            'RTT*JUP|BR': 'RTT*JUP|BR',
            'RTT*JDN|LB*': 'RTT*JDN|LB*',
            'RTT*JDN|RB*': 'RTT*JDN|RB*'
        ],
        'Rotate with Jump 1': [
            'RTT*JDN1|L': 'RTT*JDN1|L',
            'RTT*JDN1|R': 'RTT*JDN1|R',
            'RTT*JDN1|T': 'RTT*JDN1|T',
            'RTT*JDN1|B': 'RTT*JDN1|B',
            'RTT*JUP1|L': 'RTT*JUP1|L',
            'RTT*JUP1|R': 'RTT*JUP1|R',
            'RTT*JUP1|T': 'RTT*JUP1|T',
            'RTT*JUP1|B': 'RTT*JUP1|B',
            'RTT*JDN1|TL': 'RTT*JDN1|TL',
            'RTT*JDN1|TR': 'RTT*JDN1|TR',
            'RTT*JDN1|BL': 'RTT*JDN1|BL',
            'RTT*JUP1|TL': 'RTT*JUP1|TL',
            'RTT*JUP1|TR': 'RTT*JUP1|TR',
            'RTT*JUP1|BL': 'RTT*JUP1|BL'
        ],
        'Rotate with Wave': [
            'RTT*WVC|LT': 'RTT*WVC|LT',
            'RTT*WVC|LB': 'RTT*WVC|LB',
            'RTT*WVC|RT': 'RTT*WVC|RT',
            'RTT*WVC|RB': 'RTT*WVC|RB',
            'RTT*WVC|TL': 'RTT*WVC|TL',
            'RTT*WVC|TR': 'RTT*WVC|TR',
            'RTT*WVC|BL': 'RTT*WVC|BL',
            'RTT*WVC|BR': 'RTT*WVC|BR',
            'RTT*WVR|LT': 'RTT*WVR|LT',
            'RTT*WVR|LB': 'RTT*WVR|LB',
            'RTT*WVR|RT': 'RTT*WVR|RT',
            'RTT*WVR|RB': 'RTT*WVR|RB',
            'RTT*WVR|TL': 'RTT*WVR|TL',
            'RTT*WVR|TR': 'RTT*WVR|TR',
            'RTT*WVR|BL': 'RTT*WVR|BL',
            'RTT*WVR|BR': 'RTT*WVR|BR'
        ],
        'Rotate with Wave with Jump 1': [
            'RTT*WV*J1|LT': 'RTT*WV*J1|LT',
            'RTT*WV*J1|LB': 'RTT*WV*J1|LB',
            'RTT*WV*J1|RT': 'RTT*WV*J1|RT',
            'RTT*WV*J1|RB': 'RTT*WV*J1|RB',
            'RTT*WV*J1|TL': 'RTT*WV*J1|TL',
            'RTT*WV*J1|TR': 'RTT*WV*J1|TR',
            'RTT*WV*J1|BL': 'RTT*WV*J1|BL',
            'RTT*WV*J1|BR': 'RTT*WV*J1|BR'
        ],
        'Rotate with Wave with Jump 2': [
            'RTT*WV*J2|LT': 'RTT*WV*J2|LT',
            'RTT*WV*J2|LB': 'RTT*WV*J2|LB',
            'RTT*WV*J2|RT': 'RTT*WV*J2|RT',
            'RTT*WV*J2|RB': 'RTT*WV*J2|RB',
            'RTT*WV*J2|TL': 'RTT*WV*J2|TL',
            'RTT*WV*J2|TR': 'RTT*WV*J2|TR',
            'RTT*WV*J2|BL': 'RTT*WV*J2|BL',
            'RTT*WV*J2|BR': 'RTT*WV*J2|BR'
        ],
        'Rotate with Wave with Jump 3': [
            'RTT*WV*J3|LT': 'RTT*WV*J3|LT',
            'RTT*WV*J3|LB': 'RTT*WV*J3|LB',
            'RTT*WV*J3|RT': 'RTT*WV*J3|RT',
            'RTT*WV*J3|RB': 'RTT*WV*J3|RB',
            'RTT*WV*J3|TL': 'RTT*WV*J3|TL',
            'RTT*WV*J3|TR': 'RTT*WV*J3|TR',
            'RTT*WV*J3|BL': 'RTT*WV*J3|BL',
            'RTT*WV*J3|BR': 'RTT*WV*J3|BR'
        ],
        'Dodge': [
            'DDG|TL': 'DDG|TL',
            'DDG|TR': 'DDG|TR',
            'DDG|BL': 'DDG|BL',
            'DDG|BR': 'DDG|BR',
            'DDGDANCE|LT': 'DDGDANCE|LT',
            'DDGDANCE|RT': 'DDGDANCE|RT',
            'DDGDANCE|LB': 'DDGDANCE|LB',
            'DDGDANCE|RB': 'DDGDANCE|RB',
            'DDGPET|LT': 'DDGPET|LT',
            'DDGPET|LB': 'DDGPET|LB',
            'DDGPET|RT': 'DDGPET|RT',
            'DDGPET|RB': 'DDGPET|RB'
        ],
        'Flutter': [
            'FLTTR|L': 'FLTTR|L',
            'FLTTR|R': 'FLTTR|R',
            'FLTTR|T': 'FLTTR|T',
            'FLTTR|B': 'FLTTR|B',
            'FLTTRWN|LT': 'FLTTRWN|LT',
            'FLTTRWN|LB': 'FLTTRWN|LB',
            'FLTTRWN|RT': 'FLTTRWN|RT',
            'FLTTRWN|RB': 'FLTTRWN|RB',
            'FLTTRWN|TL': 'FLTTRWN|TL',
            'FLTTRWN|TR': 'FLTTRWN|TR',
            'FLTTRWN|BL': 'FLTTRWN|BL',
            'FLTTRWN|BR': 'FLTTRWN|BR'
        ],
        'Latency': [
            'LATENCY|LT': 'LATENCY|LT',
            'LATENCY|LB': 'LATENCY|LB',
            'LATENCY|RT': 'LATENCY|RT',
            'LATENCY|RB': 'LATENCY|RB',
            'LATENCY|TL': 'LATENCY|TL',
            'LATENCY|TR': 'LATENCY|TR',
            'LATENCY|BL': 'LATENCY|BL',
            'LATENCY|BR': 'LATENCY|BR'
        ],
        'Tortuous': [
            'TORTUOUS|HL': 'TORTUOUS|HL',
            'TORTUOUS|HR': 'TORTUOUS|HR',
            'TORTUOUS|VB': 'TORTUOUS|VB',
            'TORTUOUS|VT': 'TORTUOUS|VT',
            'TORTUOUS|LT': 'TORTUOUS|LT',
            'TORTUOUS|LB': 'TORTUOUS|LB',
            'TORTUOUS|RT': 'TORTUOUS|RT',
            'TORTUOUS|RB': 'TORTUOUS|RB',
            'TORTUOUS|TL': 'TORTUOUS|TL',
            'TORTUOUS|TR': 'TORTUOUS|TR',
            'TORTUOUS|BL': 'TORTUOUS|BL',
            'TORTUOUS|BR': 'TORTUOUS|BR'
        ],
        'Spaceship': [
            'SPACESHIP|LT': 'SPACESHIP|LT',
            'SPACESHIP|LB': 'SPACESHIP|LB',
            'SPACESHIP|RT': 'SPACESHIP|RT',
            'SPACESHIP|RB': 'SPACESHIP|RB',
        ],
        'Attack': [
            'ATTACK|LT': 'ATTACK|LT',
            'ATTACK|LB': 'ATTACK|LB',
            'ATTACK|RT': 'ATTACK|RT',
            'ATTACK|RB': 'ATTACK|RB',
            'ATTACK|TL': 'ATTACK|TL',
            'ATTACK|TR': 'ATTACK|TR',
            'ATTACK|BL': 'ATTACK|BL',
            'ATTACK|BR': 'ATTACK|BR'
        ],
        'List': [
            'LISTV|L': 'LISTV|L',
            'LISTV|R': 'LISTV|R',
            'LISTH|L': 'LISTH|L',
            'LISTH|R': 'LISTH|R',
            'LISTVC|L': 'LISTVC|L',
            'LISTVC|R': 'LISTVC|R',
            'LISTVC|B': 'LISTVC|B',
            'LISTVC|T': 'LISTVC|T',
            'LISTHC|L': 'LISTHC|L',
            'LISTHC|R': 'LISTHC|R',
            'LISTHC|B': 'LISTHC|B',
            'LISTHC|T': 'LISTHC|T',
        ],
        'Wave': [
            'WV|L': 'WV|L',
            'WV|R': 'WV|R',
            'WV|T': 'WV|T',
            'WV|B': 'WV|B',
            'WVC|L': 'WVC|L',
            'WVC|R': 'WVC|R',
            'WVC|T': 'WVC|T',
            'WVC|B': 'WVC|B',
            'WVR|L': 'WVR|L',
            'WVR|R': 'WVR|R'
        ],

        'Jump': [
            'JDN|L': 'JDN|L',
            'JDN|R': 'JDN|R',
            'JDN|T': 'JDN|T',
            'JDN|B': 'JDN|B',
            'JUP|L': 'JUP|L',
            'JUP|R': 'JUP|R',
            'JUP|T': 'JUP|T',
            'JUP|B': 'JUP|B'
        ],
        'Fade': [
            'FADE': 'FADE'
        ],

        'Fade with Jump': [
            'FADE*JDN|L': 'FADE*JDN|L',
            'FADE*JDN|R': 'FADE*JDN|R',
            'FADE*JDN|T': 'FADE*JDN|T',
            'FADE*JDN|B': 'FADE*JDN|B',
            'FADE*JUP|L': 'FADE*JUP|L',
            'FADE*JUP|R': 'FADE*JUP|R',
            'FADE*JUP|T': 'FADE*JUP|T',
            'FADE*JUP|B': 'FADE*JUP|B'
        ],
        'Move - Jump': [
            'L-JDN': 'L-JDN',
            'R-JDN': 'R-JDN',
            'T-JDN': 'T-JDN',
            'B-JDN': 'B-JDN',
            'L-JUP': 'L-JUP',
            'R-JUP': 'R-JUP',
            'T-JUP': 'T-JUP',
            'B-JUP': 'B-JUP'
        ],
        'Move - Wave': [
            'L-WVC': 'L-WVC',
            'R-WVC': 'R-WVC',
            'T-WVC': 'T-WVC',
            'B-WVC': 'B-WVC',
            'L-WVR': 'L-WVR',
            'R-WVR': 'R-WVR',
            'T-WVR': 'T-WVR',
            'B-WVR': 'B-WVR'
        ],
        'Clip - Fade': [
            'CLIP-FADE': 'CLIP-FADE',
            'CLIP|LR-FADE': 'CLIP|LR-FADE',
            'CLIP|TB-FADE': 'CLIP|TB-FADE',
            'CLIP|L-FADE': 'CLIP|L-FADE',
            'CLIP|R-FADE': 'CLIP|R-FADE',
            'CLIP|T-FADE': 'CLIP|T-FADE',
            'CLIP|B-FADE': 'CLIP|B-FADE'
        ],
        'MClip - Fade': [
            'MCLIP|L-FADE': 'MCLIP|L-FADE',
            'MCLIP|R-FADE': 'MCLIP|R-FADE',
            'MCLIP|T-FADE': 'MCLIP|T-FADE',
            'MCLIP|B-FADE': 'MCLIP|B-FADE'
        ],
        'Move with Clip': [
            'L*CLIP': 'L*CLIP',
            'R*CLIP': 'R*CLIP',
            'T*CLIP': 'T*CLIP',
            'B*CLIP': 'B*CLIP'
        ],
        'Move - out*': [
            'T-L*': 'T-L*',
            'T-R*': 'T-R*',
            'B-L*': 'B-L*',
            'B-R*': 'B-R*',
            'L-T*': 'L-T*',
            'L-B*': 'L-B*',
            'R-T*': 'R-T*',
            'R-B*': 'R-B*',
        ],
        'Fade - out*': [
            'FADE-L*': 'FADE-L*',
            'FADE-R*': 'FADE-R*',
            'FADE-T*': 'FADE-T*',
            'FADE-B*': 'FADE-B*'
        ],
    ]*/

    public static SLIDE_TRANSITIONS = [
        'Shift': [
            'Shift Left Right': 'Shift LR',
            'Shift Top Bottom': 'Shift TB'
        ],
        'Fade': [
            'Fade': 'Fade',
            'Fade in Left': 'Fade in L',
            'Fade in Right': 'Fade in R',
            'Fade in Top': 'Fade in T',
            'Fade in Bottom': 'Fade in B',
            'Fade Random': 'Fade Random'
        ],
        'Zoom': [
            'Zoom+ In': 'Zoom+ in',
            'Zoom+ Out': 'Zoom+ out'
        ],
        'Slide': [
            'Slide Down': 'Slide Down',
        ],
        'Float': [
             'Up Random': 'Float up Random'
        ]
    ]

    /*public static SLIDE_TRANSITIONS = [
        'Twins Effects': [
            'Fade Twins': 'Fade Twins',
            'Rotate Overlap': 'Rotate Overlap',
            'Switch': 'Switch',
            'Rotate Relay': 'Rotate Relay',
            'Doors': 'Doors',
            'Rotate in+ out-': 'Rotate in+ out-',
            'Fly Twins': 'Fly Twins',
            'Rotate in- out+': 'Rotate in- out+',
            'Rotate Axis up overlap': 'Rotate Axis up overlap',
            'Chess Replace TB': 'Chess Replace TB',
            'Chess Replace LR': 'Chess Replace LR',
            'Shift TB': 'Shift TB',
            'Shift LR': 'Shift LR',
            'Return TB': 'Return TB',
            'Return LR': 'Return LR',
            'Rotate Axis down': 'Rotate Axis down',
            'Extrude Replace': 'Extrude Replace'
        ],
        'Fade Effects': [
            'Fade': 'Fade',
            'Fade in L': 'Fade in L',
            'Fade in R': 'Fade in R',
            'Fade in T': 'Fade in T',
            'Fade in B': 'Fade in B',
            'Fade in LR': 'Fade in LR',
            'Fade in LR Chess': 'Fade in LR Chess',
            'Fade in TB': 'Fade in TB',
            'Fade in TB Chess': 'Fade in TB Chess',
            'Fade in Corners': 'Fade in Corners',
            'Fade out L': 'Fade out L',
            'Fade out R': 'Fade out R',
            'Fade out T': 'Fade out T',
            'Fade out B': 'Fade out B',
            'Fade out LR': 'Fade out LR',
            'Fade out LR Chess': 'Fade out LR Chess',
            'Fade out TB': 'Fade out TB',
            'Fade out TB Chess': 'Fade out TB Chess',
            'Fade out Corners': 'Fade out Corners',
            'Fade Fly in L': 'Fade Fly in L',
            'Fade Fly in R': 'Fade Fly in R',
            'Fade Fly in T': 'Fade Fly in T',
            'Fade Fly in B': 'Fade Fly in B',
            'Fade Fly in LR': 'Fade Fly in LR',
            'Fade Fly in LR Chess': 'Fade Fly in LR Chess',
            'Fade Fly in TB': 'Fade Fly in TB',
            'Fade Fly in TB Chess': 'Fade Fly in TB Chess',
            'Fade Fly in Corners': 'Fade Fly in Corners',
            'Fade Fly out L': 'Fade Fly out L',
            'Fade Fly out R': 'Fade Fly out R',
            'Fade Fly out T': 'Fade Fly out T',
            'Fade Fly out B': 'Fade Fly out B',
            'Fade Fly out LR': 'Fade Fly out LR',
            'Fade Fly out LR Chess': 'Fade Fly out LR Chess',
            'Fade Fly out TB': 'Fade Fly out TB',
            'Fade Fly out TB Chess': 'Fade Fly out TB Chess',
            'Fade Fly out Corners': 'Fade Fly out Corners',
            'Fade Clip in H': 'Fade Clip in H',
            'Fade Clip in V': 'Fade Clip in V',
            'Fade Clip out H': 'Fade Clip out H',
            'Fade Clip out V': 'Fade Clip out V',
            'Fade Stairs': 'Fade Stairs',
            'Fade Random': 'Fade Random',
            'Fade Swirl': 'Fade Swirl',
            'Fade ZigZag': 'Fade ZigZag'
        ],
        'Swing Outside Effects': [
            'Swing Outside in Stairs': 'Swing Outside in Stairs',
            'Swing Outside in ZigZag': 'Swing Outside in ZigZag',
            'Swing Outside in Swirl': 'Swing Outside in Swirl',
            'Swing Outside in Random': 'Swing Outside in Random',
            'Swing Outside in Random Chess': 'Swing Outside in Random Chess',
            'Swing Outside in Square': 'Swing Outside in Square',
            'Swing Outside out Stairs': 'Swing Outside out Stairs',
            'Swing Outside out ZigZag': 'Swing Outside out ZigZag',
            'Swing Outside out Swirl': 'Swing Outside out Swirl',
            'Swing Outside out Random': 'Swing Outside out Random',
            'Swing Outside out Random Chess': 'Swing Outside out Random Chess',
            'Swing Outside out Square': 'Swing Outside out Square'
        ],
        'Swing Inside Effects': [
            'Swing Inside in Stairs': 'Swing Inside in Stairs',
            'Swing Inside in ZigZag': 'Swing Inside in ZigZag',
            'Swing Inside in Swirl': 'Swing Inside in Swirl',
            'Swing Inside in Random': 'Swing Inside in Random',
            'Swing Inside in Random Chess': 'Swing Inside in Random Chess',
            'Swing Inside in Square': 'Swing Inside in Square',
            'Swing Inside out ZigZag': 'Swing Inside out ZigZag',
            'Swing Inside out Swirl': 'Swing Inside out Swirl'
        ],
        'Dodge Dance Outside Effects': [
            'Dodge Dance Outside in Stairs': 'Dodge Dance Outside in Stairs',
            'Dodge Dance Outside in Swirl': 'Dodge Dance Outside in Swirl',
            'Dodge Dance Outside in ZigZag': 'Dodge Dance Outside in ZigZag',
            'Dodge Dance Outside in Random': 'Dodge Dance Outside in Random',
            'Dodge Dance Outside in Random Chess': 'Dodge Dance Outside in Random Chess',
            'Dodge Dance Outside in Square': 'Dodge Dance Outside in Square',
            'Dodge Dance Outside out Stairs': 'Dodge Dance Outside out Stairs',
            'Dodge Dance Outside out Swirl': 'Dodge Dance Outside out Swirl',
            'Dodge Dance Outside out ZigZag': 'Dodge Dance Outside out ZigZag',
            'Dodge Dance Outside out Random': 'Dodge Dance Outside out Random',
            'Dodge Dance Outside out Random Chess': 'Dodge Dance Outside out Random Chess',
            'Dodge Dance Outside out Square': 'Dodge Dance Outside out Square'
        ],
        'Dodge Dance Inside Effects': [
            'Dodge Dance Inside in Stairs': 'Dodge Dance Inside in Stairs',
            'Dodge Dance Inside in Swirl': 'Dodge Dance Inside in Swirl',
            'Dodge Dance Inside in ZigZag': 'Dodge Dance Inside in ZigZag',
            'Dodge Dance Inside in Random': 'Dodge Dance Inside in Random',
            'Dodge Dance Inside in Random Chess': 'Dodge Dance Inside in Random Chess',
            'Dodge Dance Inside in Square': 'Dodge Dance Inside in Square',
            'Dodge Dance Inside out Stairs': 'Dodge Dance Inside out Stairs',
            'Dodge Dance Inside out Swirl': 'Dodge Dance Inside out Swirl',
            'Dodge Dance Inside out ZigZag': 'Dodge Dance Inside out ZigZag',
            'Dodge Dance Inside out Random': 'Dodge Dance Inside out Random',
            'Dodge Dance Inside out Random Chess': 'Dodge Dance Inside out Random Chess',
            'Dodge Dance Inside out Square': 'Dodge Dance Inside out Square'
        ],

        'Dodge Pet Outside Effects': [
            'Dodge Pet Outside in Stairs': 'Dodge Pet Outside in Stairs',
            'Dodge Pet Outside in Swirl': 'Dodge Pet Outside in Swirl',
            'Dodge Pet Outside in ZigZag': 'Dodge Pet Outside in ZigZag',
            'Dodge Pet Outside in Random': 'Dodge Pet Outside in Random',
            'Dodge Pet Outside in Random Chess': 'Dodge Pet Outside in Random Chess',
            'Dodge Pet Outside in Square': 'Dodge Pet Outside in Square',
            'Dodge Pet Outside out Stairs': 'Dodge Pet Outside out Stairs',
            'Dodge Pet Outside out Swirl': 'Dodge Pet Outside out Swirl',
            'Dodge Pet Outside out ZigZag': 'Dodge Pet Outside out ZigZag',
            'Dodge Pet Outside out Random': 'Dodge Pet Outside out Random',
            'Dodge Pet Outside out Random Chess': 'Dodge Pet Outside out Random Chess',
            'Dodge Pet Outside out Square': 'Dodge Pet Outside out Square'
        ],
        'Dodge Pet Inside Effects': [
            'Dodge Pet Inside in Stairs': 'Dodge Pet Inside in Stairs',
            'Dodge Pet Inside in Swirl': 'Dodge Pet Inside in Swirl',
            'Dodge Pet Inside in ZigZag': 'Dodge Pet Inside in ZigZag',
            'Dodge Pet Inside in Random': 'Dodge Pet Inside in Random',
            'Dodge Pet Inside in Random Chess': 'Dodge Pet Inside in Random Chess',
            'Dodge Pet Inside in Square': 'Dodge Pet Inside in Square',
            'Dodge Pet Inside out Stairs': 'Dodge Pet Inside out Stairs',
            'Dodge Pet Inside out Swirl': 'Dodge Pet Inside out Swirl',
            'Dodge Pet Inside out ZigZag': 'Dodge Pet Inside out ZigZag',
            'Dodge Pet Inside out Random': 'Dodge Pet Inside out Random',
            'Dodge Pet Inside out Random Chess': 'Dodge Pet Inside out Random Chess',
            'Dodge Pet Inside out Square': 'Dodge Pet Inside out Square'
        ],
        'Dodge Outside Effects': [
            'Dodge Outside out Stairs': 'Dodge Outside out Stairs',
            'Dodge Outside out Swirl': 'Dodge Outside out Swirl',
            'Dodge Outside out ZigZag': 'Dodge Outside out ZigZag',
            'Dodge Outside out Random': 'Dodge Outside out Random',
            'Dodge Outside out Random Chess': 'Dodge Outside out Random Chess',
            'Dodge Outside out Square': 'Dodge Outside out Square',
            'Dodge Outside in Stairs': 'Dodge Outside in Stairs',
            'Dodge Outside in Swirl': 'Dodge Outside in Swirl',
            'Dodge Outside in ZigZag': 'Dodge Outside in ZigZag',
            'Dodge Outside in Random': 'Dodge Outside in Random',
            'Dodge Outside in Random Chess': 'Dodge Outside in Random Chess',
            'Dodge Outside in Square': 'Dodge Outside in Square'
        ],
        'Dodge Inside Effects': [
            'Dodge Inside out Stairs': 'Dodge Inside out Stairs',
            'Dodge Inside out Swirl': 'Dodge Inside out Swirl',
            'Dodge Inside out ZigZag': 'Dodge Inside out ZigZag',
            'Dodge Inside out Random': 'Dodge Inside out Random',
            'Dodge Inside out Random Chess': 'Dodge Inside out Random Chess',
            'Dodge Inside out Square': 'Dodge Inside out Square',
            'Dodge Inside in Stairs': 'Dodge Inside in Stairs',
            'Dodge Inside in Swirl': 'Dodge Inside in Swirl',
            'Dodge Inside in ZigZag': 'Dodge Inside in ZigZag',
            'Dodge Inside in Random': 'Dodge Inside in Random',
            'Dodge Inside in Random Chess': 'Dodge Inside in Random Chess',
            'Dodge Inside in Square': 'Dodge Inside in Square',
            'Dodge Inside in TL': 'Dodge Inside in TL',
            'Dodge Inside in TR': 'Dodge Inside in TR',
            'Dodge Inside in BL': 'Dodge Inside in BL',
            'Dodge Inside in BR': 'Dodge Inside in BR',
            'Dodge Inside out TL': 'Dodge Inside out TL',
            'Dodge Inside out TR': 'Dodge Inside out TR',
            'Dodge Inside out BL': 'Dodge Inside out BL',
            'Dodge Inside out BR': 'Dodge Inside out BR'
        ],
        'Flutter Outside Effects': [
            'Flutter Outside in': 'Flutter Outside in',
            'Flutter Outside in Wind': 'Flutter Outside in Wind',
            'Flutter Outside in Swirl': 'Flutter Outside in Swirl',
            'Flutter Outside in Column': 'Flutter Outside in Column',
            'Flutter Outside out': 'Flutter Outside out',
            'Flutter Outside out Wind': 'Flutter Outside out Wind',
            'Flutter Outside out Swirl': 'Flutter Outside out Swirl',
            'Flutter Outside out Column': 'Flutter Outside out Column'
        ],
        'Flutter Inside Effects': [
            'Flutter Inside in': 'Flutter Inside in',
            'Flutter Inside in Wind': 'Flutter Inside in Wind',
            'Flutter Inside in Swirl': 'Flutter Inside in Swirl',
            'Flutter Inside in Column': 'Flutter Inside in Column',
            'Flutter Inside out': 'Flutter Inside out',
            'Flutter Inside out Wind': 'Flutter Inside out Wind',
            'Flutter Inside out Swirl': 'Flutter Inside out Swirl',
            'Flutter Inside out Column': 'Flutter Inside out Column'
        ],
        'Rotate Effects': [
            'Rotate VDouble+ in': 'Rotate VDouble+ in',
            'Rotate HDouble+ in': 'Rotate HDouble+ in',
            'Rotate VDouble- in': 'Rotate VDouble- in',
            'Rotate HDouble- in': 'Rotate HDouble- in',
            'Rotate VDouble+ out': 'Rotate VDouble+ out',
            'Rotate HDouble+ out': 'Rotate HDouble+ out',
            'Rotate VDouble- out': 'Rotate VDouble- out',
            'Rotate HDouble- out': 'Rotate HDouble- out',
            'Rotate VFork+ in': 'Rotate VFork+ in',
            'Rotate HFork+ in': 'Rotate HFork+ in',
            'Rotate VFork+ out': 'Rotate VFork+ out',
            'Rotate HFork+ out': 'Rotate HFork+ out',
            'Rotate Zoom+ in': 'Rotate Zoom+ in',
            'Rotate Zoom+ in L': 'Rotate Zoom+ in L',
            'Rotate Zoom+ in R': 'Rotate Zoom+ in R',
            'Rotate Zoom+ in T': 'Rotate Zoom+ in T',
            'Rotate Zoom+ in B': 'Rotate Zoom+ in B',
            'Rotate Zoom+ in TL': 'Rotate Zoom+ in TL',
            'Rotate Zoom+ in TR': 'Rotate Zoom+ in TR',
            'Rotate Zoom+ in BL': 'Rotate Zoom+ in BL',
            'Rotate Zoom+ in BR': 'Rotate Zoom+ in BR',
            'Rotate Zoom+ out': 'Rotate Zoom+ out',
            'Rotate Zoom+ out L': 'Rotate Zoom+ out L',
            'Rotate Zoom+ out R': 'Rotate Zoom+ out R',
            'Rotate Zoom+ out T': 'Rotate Zoom+ out T',
            'Rotate Zoom+ out B': 'Rotate Zoom+ out B',
            'Rotate Zoom+ out TL': 'Rotate Zoom+ out TL',
            'Rotate Zoom+ out TR': 'Rotate Zoom+ out TR',
            'Rotate Zoom+ out BL': 'Rotate Zoom+ out BL',
            'Rotate Zoom+ out BR': 'Rotate Zoom+ out BR',
            'Rotate Zoom- in': 'Rotate Zoom- in',
            'Rotate Zoom- in L': 'Rotate Zoom- in L',
            'Rotate Zoom- in R': 'Rotate Zoom- in R',
            'Rotate Zoom- in T': 'Rotate Zoom- in T',
            'Rotate Zoom- in B': 'Rotate Zoom- in B',
            'Rotate Zoom- in TL': 'Rotate Zoom- in TL',
            'Rotate Zoom- in TR': 'Rotate Zoom- in TR',
            'Rotate Zoom- in BL': 'Rotate Zoom- in BL',
            'Rotate Zoom- in BR': 'Rotate Zoom- in BR',
            'Rotate Zoom- out': 'Rotate Zoom- out',
            'Rotate Zoom- out L': 'Rotate Zoom- out L',
            'Rotate Zoom- out R': 'Rotate Zoom- out R',
            'Rotate Zoom- out T': 'Rotate Zoom- out T',
            'Rotate Zoom- out B': 'Rotate Zoom- out B',
            'Rotate Zoom- out TL': 'Rotate Zoom- out TL',
            'Rotate Zoom- out TR': 'Rotate Zoom- out TR',
            'Rotate Zoom- out BL': 'Rotate Zoom- out BL',
            'Rotate Zoom- out BR': 'Rotate Zoom- out BR'
        ],
        'Zoom Effect': [
            'Zoom VDouble+ in': 'Zoom VDouble+ in',
            'Zoom HDouble+ in': 'Zoom HDouble+ in',
            'Zoom VDouble- in': 'Zoom VDouble- in',
            'Zoom HDouble- in': 'Zoom HDouble- in',
            'Zoom VDouble+ out': 'Zoom VDouble+ out',
            'Zoom HDouble+ out': 'Zoom HDouble+ out',
            'Zoom VDouble- out': 'Zoom VDouble- out',
            'Zoom HDouble- out': 'Zoom HDouble- out',
            'Zoom+ in': 'Zoom+ in',
            'Zoom+ in L': 'Zoom+ in L',
            'Zoom+ in R': 'Zoom+ in R',
            'Zoom+ in T': 'Zoom+ in T',
            'Zoom+ in B': 'Zoom+ in B',
            'Zoom+ in TL': 'Zoom+ in TL',
            'Zoom+ in TR': 'Zoom+ in TR',
            'Zoom+ in BL': 'Zoom+ in BL',
            'Zoom+ in BR': 'Zoom+ in BR',
            'Zoom+ out': 'Zoom+ out',
            'Zoom+ out L': 'Zoom+ out L',
            'Zoom+ out R': 'Zoom+ out R',
            'Zoom+ out T': 'Zoom+ out T',
            'Zoom+ out B': 'Zoom+ out B',
            'Zoom+ out TL': 'Zoom+ out TL',
            'Zoom+ out TR': 'Zoom+ out TR',
            'Zoom+ out BL': 'Zoom+ out BL',
            'Zoom+ out BR': 'Zoom+ out BR',
            'Zoom- in': 'Zoom- in',
            'Zoom- in L': 'Zoom- in L',
            'Zoom- in R': 'Zoom- in R',
            'Zoom- in T': 'Zoom- in T',
            'Zoom- in B': 'Zoom- in B',
            'Zoom- in TL': 'Zoom- in TL',
            'Zoom- in TR': 'Zoom- in TR',
            'Zoom- in BL': 'Zoom- in BL',
            'Zoom- in BR': 'Zoom- in BR',
            'Zoom- out': 'Zoom- out',
            'Zoom- out L': 'Zoom- out L',
            'Zoom- out R': 'Zoom- out R',
            'Zoom- out T': 'Zoom- out T',
            'Zoom- out B': 'Zoom- out B',
            'Zoom- out TL': 'Zoom- out TL',
            'Zoom- out TR': 'Zoom- out TR',
            'Zoom- out BL': 'Zoom- out BL',
            'Zoom- out BR': 'Zoom- out BR'
        ],
        'Collapse Effects': [
            'Collapse Stairs': 'Collapse Stairs',
            'Collapse Swirl': 'Collapse Swirl',
            'Collapse Square': 'Collapse Square',
            'Collapse Rectangle Cross': 'Collapse Rectangle Cross',
            'Collapse Rectangle': 'Collapse Rectangle',
            'Collapse Cross': 'Collapse Cross',
            'Collapse Circle': 'Collapse Circle',
            'Collapse ZigZag': 'Collapse ZigZag',
            'Collapse Random': 'Collapse Random'
        ],
        'Compound Effects': [
            'Clip &amp; Chess in': 'Clip &amp; Chess in',
            'Clip &amp; Chess out': 'Clip &amp; Chess out',
            'Clip &amp; Oblique Chess in': 'Clip &amp; Oblique Chess in',
            'Clip &amp; Oblique Chess out': 'Clip &amp; Oblique Chess out',
            'Clip &amp; Wave in': 'Clip &amp; Wave in',
            'Clip &amp; Wave out': 'Clip &amp; Wave out',
            'Clip &amp; Jump in': 'Clip &amp; Jump in',
            'Clip &amp; Jump out': 'Clip &amp; Jump out'
        ],
        'Expand Effects': [
            'Expand Stairs': 'Expand Stairs',
            'Expand Straight': 'Expand Straight',
            'Expand Swirl': 'Expand Swirl',
            'Expand Square': 'Expand Square',
            'Expand Rectangle Cross': 'Expand Rectangle Cross',
            'Expand Rectangle': 'Expand Rectangle',
            'Expand Cross': 'Expand Cross',
            'Expand ZigZag': 'Expand ZigZag',
            'Expand Random': 'Expand Random'
        ],
        'Stripe Effects': [
            'Dominoes Stripe': 'Dominoes Stripe',
            'Extrude out Stripe': 'Extrude out Stripe',
            'Extrude in Stripe': 'Extrude in Stripe',
            'Horizontal Blind Stripe': 'Horizontal Blind Stripe',
            'Vertical Blind Stripe': 'Vertical Blind Stripe',
            'Horizontal Stripe': 'Horizontal Stripe',
            'Vertical Stripe': 'Vertical Stripe',
            'Horizontal Moving Stripe': 'Horizontal Moving Stripe',
            'Vertical Moving Stripe': 'Vertical Moving Stripe',
            'Horizontal Fade Stripe': 'Horizontal Fade Stripe',
            'Vertical Fade Stripe': 'Vertical Fade Stripe',
            'Horizontal Fly Stripe': 'Horizontal Fly Stripe',
            'Vertical Fly Stripe': 'Vertical Fly Stripe',
            'Horizontal Chess Stripe': 'Horizontal Chess Stripe',
            'Vertical Chess Stripe': 'Vertical Chess Stripe',
            'Horizontal Random Fade Stripe': 'Horizontal Random Fade Stripe',
            'Vertical Random Fade Stripe': 'Vertical Random Fade Stripe',
            'Horizontal Bounce Stripe': 'Horizontal Bounce Stripe',
            'Vertical Bounce Stripe': 'Vertical Bounce Stripe',
        ],
        'Wave out Effects': [
            'Wave out': 'Wave out',
            'Wave out Eagle': 'Wave out Eagle',
            'Wave out Swirl': 'Wave out Swirl',
            'Wave out ZigZag': 'Wave out ZigZag',
            'Wave out Square': 'Wave out Square',
            'Wave out Rectangle': 'Wave out Rectangle',
            'Wave out Circle': 'Wave out Circle',
            'Wave out Cross': 'Wave out Cross',
            'Wave out Rectangle Cross': 'Wave out Rectangle Cross'
        ],
        'Wave in Effects': [
            'Wave in': 'Wave in',
            'Wave in Eagle': 'Wave in Eagle',
            'Wave in Swirl': 'Wave in Swirl',
            'Wave in ZigZag': 'Wave in ZigZag',
            'Wave in Square': 'Wave in Square',
            'Wave in Rectangle': 'Wave in Rectangle',
            'Wave in Circle': 'Wave in Circle',
            'Wave in Cross': 'Wave in Cross',
            'Wave in Rectangle Cross': 'Wave in Rectangle Cross'
        ],
        'Jump out Effects': [
            'Jump out Straight': 'Jump out Straight',
            'Jump out Swirl': 'Jump out Swirl',
            'Jump out ZigZag': 'Jump out ZigZag',
            'Jump out Square': 'Jump out Square',
            'Jump out Square with Chess': 'Jump out Square with Chess',
            'Jump out Rectangle': 'Jump out Rectangle',
            'Jump out Circle': 'Jump out Circle',
            'Jump out Rectangle Cross': 'Jump out Rectangle Cross'
        ],
        'Jump in Effects': [
            'Jump in Straight': 'Jump in Straight',
            'Jump in Swirl': 'Jump in Swirl',
            'Jump in ZigZag': 'Jump in ZigZag',
            'Jump in Square': 'Jump in Square',
            'Jump in Square with Chess': 'Jump in Square with Chess',
            'Jump in Rectangle': 'Jump in Rectangle',
            'Jump in Circle': 'Jump in Circle',
            'Jump in Rectangle Cross': 'Jump in Rectangle Cross'
        ],
        'Parabola Effects': [
            'Parabola Swirl in': 'Parabola Swirl in',
            'Parabola Swirl out': 'Parabola Swirl out',
            'Parabola ZigZag in': 'Parabola ZigZag in',
            'Parabola ZigZag out': 'Parabola ZigZag out',
            'Parabola Stairs in': 'Parabola Stairs in',
            'Parabola Stairs out': 'Parabola Stairs out'
        ],
        'Float Effects': [
            'Float Right Random': 'Float Right Random',
            'Float up Random': 'Float up Random',
            'Float up Random with Chess': 'Float up Random with Chess',
            'Float Right ZigZag': 'Float Right ZigZag',
            'Float up ZigZag': 'Float up ZigZag',
            'Float up ZigZag with Chess': 'Float up ZigZag with Chess',
            'Float Right Swirl': 'Float Right Swirl',
            'Float up Swirl': 'Float up Swirl',
            'Float up Swirl with Chess': 'Float up Swirl with Chess'
        ],
        'Fly Effects': [
            'Fly Right Random': 'Fly Right Random',
            'Fly up Random': 'Fly up Random',
            'Fly up Random with Chess': 'Fly up Random with Chess',
            'Fly Right ZigZag': 'Fly Right ZigZag',
            'Fly up ZigZag': 'Fly up ZigZag',
            'Fly up ZigZag with Chess': 'Fly up ZigZag with Chess',
            'Fly Right Swirl': 'Fly Right Swirl',
            'Fly up Swirl': 'Fly up Swirl',
            'Fly up Swirl with Chess': 'Fly up Swirl with Chess'
        ],
        'Stone Effects': [
            'Slide Down': 'Slide Down',
            'Slide Right': 'Slide Right',
            'Bounce Down': 'Bounce Down',
            'Bounce Right': 'Bounce Right'
        ],
    ]*/
}
