package com.webcommander.plugin.snippet.controllers.admin.design

import com.webcommander.plugin.snippet.Snippet
import com.webcommander.plugin.snippet.SnippetService
import grails.util.Holders


class WidgetController {

    SnippetService snippetService
    def widgetService



    def snippetShortConfig() {
        render(view: "/plugins/snippet/admin/widget/shortConfig", model: [noAdvance: true])
    }


    def saveSnippetWidget() {
        render(widgetService.saveAnyWidget("Snippet", params))
    }


    def saveSnippetWidgetAndContent() {
        params.isAutoGenerated = true;
        Long id = params.id.toLong(0);
        if (id > 0) {
            Snippet snippet = Snippet.get(id)
            if (snippet) {
                params.name = snippet?.name;
                params.isAutoGenerated = snippet?.isAutoGenerated;
            }
        }
        def savedSnippet = snippetService.saveSnippet(params);
        if (savedSnippet) {
            params.id = savedSnippet.id
            snippetService.saveContent(params);
            params.snippetId = savedSnippet.id;
            render(widgetService.saveAnyWidget("Snippet", params))
        }else{
            render(widgetService.saveAnyWidget("Snippet", params))
        }
    }
}
