package com.webcommander.controllers.admin.content

import com.webcommander.AutoGeneratedPage
import com.webcommander.common.CommonService
import com.webcommander.content.AutoPageService
import grails.converters.JSON;

class AutoPageController {
    CommonService commonService
    AutoPageService autoPageService

    def loadAppView() {
        Integer count =  autoPageService.getAutoGeneratedPagesCount(params);
        params.max = params.max ?: "10"
        params.offset = params.offset ?: "0"
        List<AutoGeneratedPage> autoPages = commonService.withOffset(params.max, params.offset, count){ max, offset, _count ->
            params.offset = offset;
            autoPageService.getAutoGeneratedPages(params)
        }
        render(view: "/admin/autoPage/appView", model: [count: count, autoPages: autoPages]);
    }

    def edit() {
        AutoGeneratedPage fixedPage = autoPageService.getAutoGeneratedPage(params.long("id"));
        render(view: "/admin/autoPage/infoEdit", model: [fixedPage: fixedPage]);
    }

    def save() {
        boolean success = autoPageService.saveAutoGeneratedPage(params)
        if(success){
            render([status: "success", message:g.message(code: "auto.page.update.success")] as JSON)
        }else{
            render([status: "error", message:g.message(code: "auto.page.not.updated")] as JSON)
        }

    }

}
