package com.webcommander

import com.webcommander.constants.DomainConstants
import com.webcommander.events.AppEventManager

class AutoPageContent {

    Long id

    String body
    String js
    String css

    AutoGeneratedPage belong

    static belongsTo = [belong: AutoGeneratedPage]

    static constraints = {
        css(nullable: true)
        js(nullable: true)
    }

    static mapping = {
        css length: 4000
        js length: 2000
        body length: 12000
    }

    public static initialize() {
        def _init = {
            if(!AutoPageContent.count()) {
                AutoGeneratedPage productPage = AutoGeneratedPage.findByName(DomainConstants.AUTO_GENERATED_PAGES.PRODUCT_PAGE)
                AutoPageContent content = new AutoPageContent()
                content.body = '<div class="v-split-container"><div id="spltr-b56b5690-4f66-459d-a529-7eec26135a2f" class="grid-block v-split"><wi:productwidget type="productName"/></div><div id="spltr-70f0b6b9-59f4-4729-9535-391cf00c7d4e" class="grid-block v-split l-fixed-container block-800"><div id="spltr-07e42076-41ee-45c4-8638-7b3b2924d6d2" class="l-fixed-left grid-block"><wi:productwidget type="productImage"/></div><div id="spltr-96ff24bf-8e83-4924-bd85-926693cd3a57" class="l-fixed-right grid-block" pad-width="400"><wi:productwidget type="productSummary"/><wi:productwidget type="productSku"/><wi:productwidget type="productCategory"/><wi:productwidget type="productManufacturer"/><wi:productwidget type="productBrand"/><wi:productwidget type="productModel"/><wi:productwidget type="stockMark"/><wi:productwidget type="price"/><wi:productwidget type="combinedProduct"/><wi:productwidget type="variation"/><wi:productwidget type="addCart"/><wi:productwidget type="likeus"/></div></div><div id="spltr-e16c3b44-f1c9-41b7-b3a8-09517709c7fe" class="grid-block v-split"><wi:productwidget type="information"/></div><div id="spltr-5f5a158f-b03f-4472-b4e8-d1be9613aeee" class="grid-block v-split"><wi:productwidget type="related"/></div></div>'
                content.css = '#spltr-07e42076-41ee-45c4-8638-7b3b2924d6d2{width:400px;flex:0 0 400px;}#spltr-96ff24bf-8e83-4924-bd85-926693cd3a57{width:auto;flex:1 1 auto;}'
                content.belong = productPage
                content.save()
            }
        }
        if(AutoGeneratedPage.count()) {
            _init()
        } else {
            AppEventManager.one("auto-generated-page-bootstrap-init", "bootstrap-init", _init)
        }
    }
}
