package com.webcommander

import com.webcommander.common.MetaTag
import com.webcommander.constants.DomainConstants
import com.webcommander.design.Layout
import com.webcommander.events.AppEventManager

class AutoGeneratedPage {

    Long id
    String name
    String title

    Boolean editorEnable = false
    Boolean isHttps = false
    Boolean disableGooglePageTracking = false;

    Date updated

    Layout layout

    Collection<MetaTag> metaTags = []

    static hasMany = [metaTags: MetaTag]

    static constraints = {
        name(unique: true, size: 2..100)
        title(size: 2..255)
    }

    static mapping = {
        metaTags cache: true
    }

    public static void initialize() {
        def _init = {
            Layout layout = Layout.first()
            def insertSQLs = [
                [DomainConstants.AUTO_GENERATED_PAGES.PRODUCT_PAGE, "%PRODUCT_NAME%", layout, true],
                [DomainConstants.AUTO_GENERATED_PAGES.CATEGORY_PAGE, "%CATEGORY_NAME%", layout, false],
                [DomainConstants.AUTO_GENERATED_PAGES.CUSTOMER_LOGIN, "Customer Login", layout, false],
                [DomainConstants.AUTO_GENERATED_PAGES.CUSTOMER_REGISTRATION, "Customer Registration", layout, false],
                [DomainConstants.AUTO_GENERATED_PAGES.CUSTOMER_PROFILE, "Customer Profile", layout, false],
                [DomainConstants.AUTO_GENERATED_PAGES.CUSTOMER_RESET_PASSWORD, "Customer Reset Password", layout, false],
                [DomainConstants.AUTO_GENERATED_PAGES.CART_PAGE, "Cart Details", layout, false],
                [DomainConstants.AUTO_GENERATED_PAGES.ARTICLE_DETAILS_PAGE, "Article Details - %ARTICLE_NAME%", layout, false],
                [DomainConstants.AUTO_GENERATED_PAGES.SEARCH_RESULT, "Search Result(s)", layout, false],
                [DomainConstants.AUTO_GENERATED_PAGES.PAYMENT_PAGE, "Credit Card Payment", layout, false],
                [DomainConstants.AUTO_GENERATED_PAGES.PAYMENT_SUCCESS_PAGE, "Payment Success", layout, false],
                [DomainConstants.AUTO_GENERATED_PAGES.CHECKOUT, "Checkout", layout, false],
                [DomainConstants.AUTO_GENERATED_PAGES.SUBSCRIBE_NEWSLETTER, "Newsletter Subscription", layout, false],
                [DomainConstants.AUTO_GENERATED_PAGES.UNSUBSCRIBE_NEWSLETTER, "Newsletter Unsubscription", layout, false],
                [DomainConstants.AUTO_GENERATED_PAGES.GUEST_CUSTOMER_ORDER_COMMENT, "Order Comment", layout, false]
            ]
            if(AutoGeneratedPage.count() == 0) {
                insertSQLs.each {
                    new AutoGeneratedPage(name: it[0], title: it[1], layout: it[2], editorEnable: it[3]).save()
                }
                AppEventManager.fire("auto-generated-page-bootstrap-init")
            }
        }
        if(Layout.count()) {
            _init()
        } else {
            AppEventManager.one("layout-bootstrap-init", "bootstrap-init", _init)
        }
    }

    def beforeValidate() {
        if(!this.updated) {
            this.updated = new Date().gmt()
        }
    }

    def beforeUpdate() {
        this.updated = new Date().gmt()
    }

    @Override
    int hashCode() {
        if (id) {
            return ("AutoGeneratedPage: " + id).hashCode();
        }
        if (name) {
            return ("AutoGeneratedPage: " + name).hashCode();
        }
        return super.hashCode()
    }

    @Override
    boolean equals(Object o) {
        if (!o instanceof AutoGeneratedPage) {
            return false
        }
        if (id && o.id) {
            return id == o.id;
        }
        if (name) {
            return name == o.name;
        }
        return super.equals(o);
    }

}
