package com.webcommander.config

import com.webcommander.admin.Country
import com.webcommander.admin.State
import com.webcommander.constants.DomainConstants
import com.webcommander.events.AppEventManager

class SiteConfig {

    Long id
    String type
    String configKey
    String value

    static constraints = {
        configKey unique: "type"
        value nullable: true
    }

    static mapping = {
        value type: "text"
    }

    static void initialize() {
        def _init = {
            if (SiteConfig.count() == 0) {
                INITIAL_DATA.each { types ->
                    types.value.each { entry ->
                        def value = entry.value;
                        if (entry.value instanceof Closure) {
                            value = entry.value.call();
                        }
                        new SiteConfig(type: types.key, configKey: entry.key, value: value).save()
                    }
                }
                AppEventManager.fire("site-config-bootstrap-init")
            }
        }
        if(State.count()) {
            _init()
        } else {
            AppEventManager.one("state-bootstrap-init", "bootstrap-init", _init)
        }
    }

    public static final INITIAL_DATA = [
            (DomainConstants.SITE_CONFIG_TYPES.AWS_S3)                        : [
                    static_enabled      : "false",
                    static_url          : "",
                    resource_enabled    : "false",
                    resource_access_key : "",
                    resource_secret_key : "",
                    resource_bucket_name: ""
            ],
            (DomainConstants.SITE_CONFIG_TYPES.CLOUD_STORAGE)                 : [
                    aws_is_enabled                : "false",
                    aws_enable_resource_bucket    : "false",
                    aws_resource_bucket_name      : "",
                    aws_resource_bucket_access_key: "",
                    aws_resource_bucket_secret_key: ""
            ],
            (DomainConstants.SITE_CONFIG_TYPES.ADMINISTRATION)                : [
                    baseurl        : "http://localhost:8080",
                    secured_baseurl: "https://localhost:8443",
                    provision      : """{"url": "", "clientId": "", "clientSecret": "", "code": "", "refreshToken": "", "accessToken": ""}""",
                    instance_id    : "00000000",
                    ecommerce      : "true",
                    enable_multi_model: "false"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.E_COMMERCE)                    : [
                    show_out_of_stock_products        : "false",
                    available_stock_message           : "s:available",
                    out_stock_message                 : "s:out.of.stock",
                    low_stock_message                 : "s:low.stock",
                    update_stock                      : DomainConstants.UPDATE_STOCK.AFTER_SHIPMENT,
                    order_quantity_over_stock         : DomainConstants.OUT_OF_STOCK_MESSAGE_TYPE.DO_NOT_SELL,
                    add_available_message             : "s:quantity.not.available.availables.added.in.cart",
                    do_not_sell_message               : "s:requested.quantity.not.available",
                    lead_day                          : "7",
                    enable_continue_shopping          : "true",
                    continue_shopping_label           : "s:continue.shopping",
                    continue_shopping_target          : "previous",
                    continue_shopping_specified_target: "",
                    enable_minimum_purchase_amount    : "false",
                    minimum_purchase_amount           : "",
                    low_stock_notification            : "false",
                    out_of_stock_notification         : "false",
                    low_stock_notification_json       : "",
                    out_of_stock_notification_json    : ""
            ],
            (DomainConstants.SITE_CONFIG_TYPES.WEBTOOL)                       : [
                    tracking_enabled          : "false",
                    tracking_id               : "",
                    page_tracking             : "on",
                    google_e_commerce_tracking: "on",
                    bing_page_tracking        : "on",
            ],
            (DomainConstants.SITE_CONFIG_TYPES.GOOGLE_EVENT_TRACKING)         : [
                    tracking                         : "off",

                    event_ecommerce                  : "off",
                    ecommerce_category               : "off",
                    ecommerce_navigation             : "off",
                    ecommerce_view_cart              : "off",
                    ecommerce_search                 : "off",

                    event_pdp                        : "off",
                    pdp_download_spec                : "off",
                    pdp_variation                    : "off",
                    pdp_shipping_calculator          : "off",
                    pdp_add_to_cart                  : "off",
                    pdp_add_to_wish_list             : "off",
                    pdp_increase_quantity            : "off",
                    pdp_decrease_quantity            : "off",
                    pdp_continue_shopping            : "off",

                    event_cartp                      : "off",
                    cartp_shipping_calculator        : "off",
                    cartp_increase_quantity          : "off",
                    cartp_decrease_quantity          : "off",
                    cartp_remove_product             : "off",
                    cartp_empty_cart                 : "off",
                    cartp_update_cart                : "off",
                    cartp_continue_shopping          : "off",
                    cartp_checkout_as_guest          : "off",
                    cartp_checkout_as_customer       : "off",

                    event_billing                    : "off",
                    billing_edit_first_Name          : "off",
                    billing_edit_last_name           : "off",
                    billing_edit_address_line        : "off",
                    billing_edit_post_code           : "off",
                    billing_edit_city                : "off",
                    billing_edit_phone               : "off",
                    billing_edit_mobile              : "off",
                    billing_edit_email               : "off",
                    billing_edit_contry              : "off",
                    billing_edit_state               : "off",
                    billing_continue                 : "off",
                    billing_cancel                   : "off",
                    billing_also_ship_to_this_address: "off",

                    event_shipping                   : "off",
                    shipping_shipping_calculator     : "off",
                    shipping_edit_first_Name         : "off",
                    shipping_edit_last_name          : "off",
                    shipping_edit_address_line       : "off",
                    shipping_edit_post_code          : "off",
                    shipping_edit_city               : "off",
                    shipping_edit_phone              : "off",
                    shipping_edit_mobile             : "off",
                    shipping_edit_email              : "off",
                    shipping_edit_contry             : "off",
                    shipping_edit_state              : "off",
                    shipping_continue                : "off",
                    shipping_cancel                  : "off",

                    event_payment                    : "off",
                    payment_pay_in_store             : "off",
                    payment_cheque                   : "off",
                    payment_money_order              : "off",
                    payment_bank_deposit             : "off",
                    payment_accounts_payable         : "off",
                    payment_store_credit             : "off",
                    payment_paypal                   : "off",
                    payment_credit_card              : "off",
                    payment_cash_on_delivery         : "off",
                    payment_loyalty_point            : "off",
                    payment_api                      : "off",
                    payment_continue                 : "off",

                    event_orderp                     : "off",
                    orderp_confirm_order             : "off",
                    orderp_order_comment             : "off",
                    orderp_order_comment_continue    : "off"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.FRONTEND_PAGES)                : [
                    body_beginning_code: "",
                    body_ending_code   : "",
                    header_code        : ""
            ],
            (DomainConstants.SITE_CONFIG_TYPES.SEARCH_PAGE)                   : [
                    entities                     : "all",
                    item_per_page                : "5",
                    submit_restricted_item       : "false",
                    search_result_view           : "list",
                    description                  : "true",
                    add_to_cart                  : "true",
                    show_on_hover                : "false",
                    price                        : "true",
                    expect_to_pay_price          : "false",
                    label_for_price              : "s:today",
                    label_for_expect_to_pay      : "s:expect.to.pay",
                    expect_to_pay_price_with_tax : "false",
                    strike_through_previous_price: "true",
                    label_for_call_for_price     : "s:call.for.price",
                    show_view_switcher           : "true"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.RELATED_PRODUCT)               : [
                    title                        : "s:related.products",
                    'item-per-page'              : "20",
                    'display-type'               : "list",
                    'show_view_switcher'         : "true",
                    description                  : "true",
                    add_to_cart                  : "true",
                    price                        : "true",
                    expect_to_pay_price          : "false",
                    label_for_price              : "s:today",
                    label_for_expect_to_pay      : "s:expect.to.pay",
                    strike_through_previous_price: "true",
                    expect_to_pay_price_with_tax : "false",
                    label_for_call_for_price     : "s:call.for.price"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.CUSTOMER_LOGIN_SETTINGS)       : [
                    name_label           : "Email",
                    password_label       : "Password",
                    reset_password_active: "activated",
                    reset_password_label : "Forgot password?",
                    reg_link_active      : "activated",
                    reg_link_label       : "Register now",
                    fail_count           : "3",
                    after_login_url      : ""
            ],
            (DomainConstants.SITE_CONFIG_TYPES.CUSTOMER_REGISTRATION_SETTINGS): [
                    close_registration_message     : "",
                    restricted_registration_message: "",
                    registration_status_type       : DomainConstants.CUSTOMER_REG_TYPE.OPEN,
                    registration_captcha           : "yes",
                    registration_terms_text        : "",
                    enable_fb_login                : 'false',
                    fb_app_id                      : '',
                    enable_google_login            : 'false',
                    google_client_id               : ''
            ],
            (DomainConstants.SITE_CONFIG_TYPES.CUSTOMER_REGISTRATION_FIELD)   : [
                    first_name_order           : "1",
                    first_name_label           : "",
                    last_name_order            : "2",
                    last_name_label            : "",
                    address_line_1_order       : "3",
                    address_line_1_label       : "",
                    address_line_2_order       : "4",
                    address_line_2_label       : "",
                    post_code_order            : "5",
                    post_code_label            : "",
                    city_order                 : "6",
                    city_label                 : "",
                    phone_order                : "7",
                    phone_label                : "",
                    mobile_order               : "8",
                    mobile_label               : "",
                    fax_order                  : "9",
                    fax_label                  : "",
                    email_order                : "10",
                    email_label                : "",
                    confirm_email_order        : "11",
                    confirm_email_label        : "",
                    password_order             : "12",
                    password_label             : "",
                    retype_password_order      : "13",
                    retype_password_label      : "",
                    country_order              : "14",
                    country_label              : "",
                    customer_type_active       : "true",
                    customer_type_required     : "false",
                    customer_type_order        : "15",
                    customer_type_label        : "",
                    sex_active                 : "1",
                    sex_required               : "0",
                    sex_order                  : "16",
                    sex_label                  : "",
                    abn_active                 : "0",
                    abn_required               : "0",
                    abn_order                  : "17",
                    abn_label                  : "",
                    abn_branch_active          : "false",
                    abn_branch_required        : "false",
                    abn_branch_order           : "18",
                    abn_branch_label           : "",
                    registration_terms_active  : "false",
                    registration_terms_required: "false",
                    registration_terms_label   : "",
                    company_name_active        : "1",
                    company_name_required      : "0",
                    company_name_order         : "19",
                    company_name_label         : ""
            ],
            (DomainConstants.SITE_CONFIG_TYPES.CUSTOMER_ACCOUNT_INFORMATION)   : [
                    first_name_order           : "1",
                    first_name_label           : "",
                    last_name_order            : "2",
                    last_name_label            : "",
                    address_line_1_order       : "3",
                    address_line_1_label       : "",
                    address_line_2_order       : "4",
                    address_line_2_label       : "",
                    post_code_order            : "5",
                    post_code_label            : "",
                    country_order              : "6",
                    country_label              : "",
                    city_order                 : "7",
                    city_label                 : "",
                    phone_order                : "8",
                    phone_label                : "",
                    mobile_order               : "9",
                    mobile_label               : "",
                    fax_order                  : "10",
                    fax_label                  : "",
                    email_order                : "11",
                    email_label                : "",
            ],
            (DomainConstants.SITE_CONFIG_TYPES.BILLING_ADDRESS_FIELD)         : [
                    first_name_order       : "1",
                    first_name_label       : "",
                    last_name_active       : "1",
                    last_name_required     : "false",
                    last_name_order        : "2",
                    last_name_label        : "",
                    address_line_1_order   : "3",
                    address_line_1_label   : "",
                    address_line_2_active  : "false",
                    address_line_2_required: "false",
                    address_line_2_order   : "4",
                    address_line_2_label   : "",
                    post_code_active       : "1",
                    post_code_required     : "1",
                    post_code_order        : "5",
                    post_code_label        : "",
                    city_active            : "1",
                    city_required          : "1",
                    city_order             : "6",
                    city_label             : "",
                    phone_active           : "1",
                    phone_required         : "false",
                    phone_order            : "7",
                    phone_label            : "",
                    mobile_active          : "1",
                    mobile_required        : "false",
                    mobile_order           : "8",
                    mobile_label           : "",
                    fax_active             : "false",
                    fax_required           : "false",
                    fax_order              : "9",
                    fax_label              : "",
                    email_order            : "10",
                    email_label            : "",
                    confirm_email_active   : "false",
                    confirm_email_required : "false",
                    confirm_email_order    : "11",
                    confirm_email_label    : "",
                    country_order          : "12",
                    country_label          : ""
            ],
            (DomainConstants.SITE_CONFIG_TYPES.SHIPPING_ADDRESS_FIELD)        : [
                    first_name_order       : "1",
                    first_name_label       : "",
                    last_name_active       : "1",
                    last_name_required     : "false",
                    last_name_order        : "2",
                    last_name_label        : "",
                    address_line_1_order   : "3",
                    address_line_1_label   : "",
                    address_line_2_active  : "false",
                    address_line_2_required: "false",
                    address_line_2_order   : "4",
                    address_line_2_label   : "",
                    post_code_active       : "1",
                    post_code_required     : "1",
                    post_code_order        : "5",
                    post_code_label        : "",
                    city_active            : "1",
                    city_required          : "1",
                    city_order             : "6",
                    city_label             : "",
                    phone_active           : "1",
                    phone_required         : "false",
                    phone_order            : "7",
                    phone_label            : "",
                    mobile_active          : "1",
                    mobile_required        : "false",
                    mobile_order           : "8",
                    mobile_label           : "",
                    fax_active             : "false",
                    fax_required           : "false",
                    fax_order              : "9",
                    fax_label              : "",
                    email_order            : "10",
                    email_label            : "",
                    confirm_email_active   : "false",
                    confirm_email_required : "false",
                    confirm_email_order    : "11",
                    confirm_email_label    : "",
                    country_order          : "12",
                    country_label          : ""
            ],
            (DomainConstants.SITE_CONFIG_TYPES.EMAIL)                         : [
                    date_format            : "EEE, d MMM yyyy",
                    time_format            : "HH:mm:ss",
                    time_zone              : "Australia/Melbourne",
                    sender_name            : 'Web Commander',
                    sender_email           : 'webcommander-smtp@webalive.biz',
                    smtp_host              : 'mail.webalive.biz',
                    smtp_port              : '587',
                    smtp_username          : 'webcommander-smtp@webalive.biz',
                    smtp_password          : 'webaliveSMTPme9',
                    smtp_encryption        : 'TLS',
                    has_smtp_authentication: "true"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.LOCALE)                        : [
                    admin_date_format: "EEE, d MMM yyyy",
                    admin_time_format: "HH:mm:ss",
                    site_date_format : "EEE, d MMM yyyy",
                    site_time_format : "HH:mm:ss"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.RESPONSIVE)                    : [
                    is_responsive: "false"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.GENERAL)                       : [
                    default_country         : { Country.findByCode("AU").id },
                    default_state           : { State.findByCode("VIC").id },
                    landing_page            : "home",
                    default_layout          : "",
                    page403                 : "",
                    page404                 : "",
                    down_page               : "",
                    unit_length             : "centimeters",
                    unit_weight             : "kilograms",
                    favicon_enabled         : "false",
                    captcha_setting         : "disable",
                    captcha_type            : "",
                    captcha_private_key     : "",
                    captcha_public_key      : "",
                    template_domain         : "",
                    template_color          : "",
                    template_uuid           : "",
                    template_container_class: "full-width",
                    theme                   : "sb",
                    auto_suggest_address    : "true",
                    max_precision           : '9',
                    favorite_widgets        : "article,html,image,product,category",
                    favorite_product_widgets: "productName,productSummary,information,addCart,productImage",
                    deployment_initialized  : "false"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.PRODUCT)                       : [
                    add_to_cart                  : 'true',
                    enable_like                  : 'true',
                    like_facebook                : 'true',
                    like_twitter                 : 'true',
                    like_pinterest               : "false",
                    like_googleplus              : 'true',
                    tell_friend                  : 'true',
                    image_zoom                   : 'true',
                    zoom_type                    : 'standard',
                    label_for_expect_to_pay      : "s:expect.to.pay",
                    label_for_base_price         : "s:todays.price",
                    strike_through_previous_price: "false",
                    expect_to_pay_price_with_tax : "false",
                    label_for_call_for_price     : "s:call.for.price",
                    show_description             : "true"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.PRODUCT_IMAGE)                 : [
                    admin_width       : "120",
                    admin_height      : "120",
                    gridview_width    : "150",
                    gridview_height   : "200",
                    listview_width    : "200",
                    listview_height   : "250",
                    details_width     : "290",
                    details_height    : "385",
                    popup_width       : "585",
                    popup_height      : "440",
                    popup_use_original: "off",
                    thumbnail_width   : "65",
                    thumbnail_height  : "50"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.CATEGORY_IMAGE)                : [
                    admin_width       : "120",
                    admin_height      : "120",
                    gridview_width    : "150",
                    gridview_height   : "200",
                    listview_width    : "200",
                    listview_height   : "250",
                    details_width     : "290",
                    details_height    : "385",
                    popup_width       : "585",
                    popup_height      : "440",
                    popup_use_original: "off",
                    thumbnail_width   : "65",
                    thumbnail_height  : "50"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.CURRENCY)                      : [
                    convert_additional_to_default: "true",
            ],
            (DomainConstants.SITE_CONFIG_TYPES.SEO_CONFIG)                    : [
                    meta_tag_name_limit       : "100",
                    meta_tag_description_limit: "350",
            ],
            (DomainConstants.SITE_CONFIG_TYPES.TAX)                           : [
                    configuration_type : "default",
                    default_country    : "australia",
                    default_tax_profile: "",
                    is_price_with_tax  : "false",
                    show_price_with_tax: "true",
                    tax_message        : "s:including.code.rate"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.CART_PAGE)                     : [
                    page_title                       : "s:shopping.cart",
                    checkout_button_text             : "s:proceed.checkout",
                    price_column_text                : "s:price",
                    item_total_label                 : "s:amount",
                    show_discount_for_each_item_label: "s:discount",
                    show_tax_for_each_item_label     : "s:tax",
                    show_total_discount_label        : "s:total.discount",
                    show_shipping_discount_label     : "s:shipping.discount",
                    show_sub_total_tax_label         : "s:sub.total.tax",
                    show_sub_total_label             : "s:sub.total",
                    show_product_thumbnail           : "true",
                    show_discount_each_item          : "false",
                    show_tax_each_item               : "false",
                    show_sub_total_tax               : "true",
                    show_total_discount              : "false",
                    show_subtotal                    : "true",
                    subtotal_price                   : "with_tax_without_discount",
                    individual_total_price           : 'with_tax_without_discount',
                    cart_empty_message               : 's:your.shopping.cart.empty',
                    price_enter_with_tax             : 'true',
                    invalid_quantity_message         : 's:invalid.quantity',
                    max_quantity_message             : 's:max.quantity.allowed',
                    min_quantity_message             : 's:min.required.quantity',
                    multiple_quantity_message        : 's:item.quantity.should.multiple'
            ],
            (DomainConstants.SITE_CONFIG_TYPES.CHECKOUT_PAGE)                 : [
                    page_title                                : "s:checkout",
                    confirm_order_button_text                 : "s:confirm.order",
                    price_column_text                         : "s:price",
                    item_total_label                          : "s:amount",
                    show_discount_for_each_item_label         : "s:discount",
                    show_tax_for_each_item_label              : "s:tax",
                    show_total_discount_label                 : "s:total.discount",
                    show_sub_total_tax_label                  : "s:sub.total.tax",
                    show_sub_total_label                      : "s:sub.total",
                    show_shipping_cost_label                  : "s:shipping.cost",
                    show_shipping_tax_label                   : "s:shipping.tax",
                    show_handling_cost_label                  : "s:handling.cost",
                    show_handling_tax_label                   : "s:handling.tax",
                    show_product_thumbnail                    : "false",
                    show_discount_each_item                   : "false",
                    show_tax_each_item                        : "false",
                    show_sub_total_tax                        : "true",
                    show_total_discount                       : "true",
                    show_checkout_as_a_guest                  : "true",
                    show_subtotal                             : "true",
                    show_shipping_cost                        : "true",
                    show_handling_cost                        : "true",
                    show_shipping_tax                         : "true",
                    show_payment_surcharge                    : "true",
                    subtotal_price                            : "with_tax_without_discount",
                    individual_total_price                    : 'with_tax_without_discount',
                    terms_and_condition                       : "false",
                    terms_and_condition_type                  : DomainConstants.TERMS_AND_CONDITION_TYPE.SPECIFIC_TEXT,
                    terms_and_condition_ref                   : "",
                    enable_comment                            : "false",
                    price_enter_with_tax                      : 'true',
                    show_handling_tax                         : 'true',
                    enable_shipping                           : 'true',
                    enable_store_pickup                       : 'false',
                    enable_others_shipping                    : 'false',
                    allow_sign_up                             : "true",
                    is_sign_up_required                       : "false",
                    show_login                                : "true",
                    shipping_display_text                     : "I want my products to be delivered",
                    shipping_display_subtext                  : "",
                    store_pickup_display_text                 : "I want to pick my products from store",
                    store_pickup_display_subtext              : "",
                    others_shipping_display_text              : "Others",
                    others_shipping_display_subtext           : "",
                    show_shipping_discount                    : "false",
                    show_shipping_discount_label              : "s:shipping.discount",
                    show_shipping_and_handling_subtext        : "false",
                    shipping_handling_subtext                 : "s:shipping.and.handling.subtext",
                    show_product_total_with_discount          : "false",
                    show_subtotal_with_discount               : "false",
                    show_shipping_and_handling_cost_separately: "false"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.ORDER_PRINT_AND_EMAIL)         : [
                    show_discount_each_item: "false",
                    show_tax_each_item     : "false",
                    show_total_discount    : "true",
                    show_sub_total_tax     : "true",
                    show_subtotal          : "true",
                    subtotal_price         : "with_tax_without_discount",
                    product_total_price    : 'with_tax_without_discount',
                    show_shipping_cost     : "true",
                    show_handling_cost     : "true",
                    show_shipping_tax      : "true",
                    show_payment_surcharge : "true"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.SHIPPING)                      : [
                    shipping_tax_profile    : "",
                    default_shipping_profile: '',
                    enable_shipping_class   : 'false',
                    default_shipping_class  : ''
            ],
            (DomainConstants.SITE_CONFIG_TYPES.CATEGORY_PAGE)                 : [
                    category_image               : "false",
                    category_description         : "false",
                    subcategory                  : "true",
                    subcategory_show_pagination  : "none",
                    subcategory_item_per_page    : "10",
                    subcategory_description      : "true",
                    show_pagination              : "none",
                    item_per_page                : "10",
                    price                        : "true",
                    description                  : "true",
                    add_to_cart                  : "true",
                    'show_view_switcher'         : "true",
                    show_on_hover                : "false",
                    item_per_page_selection      : "false",
                    sortable                     : "false",
                    expect_to_pay_price          : "false",
                    label_for_price              : "s:today",
                    label_for_expect_to_pay      : "s:expect.to.pay",
                    expect_to_pay_price_with_tax : "false",
                    strike_through_previous_price: "true",
                    label_for_call_for_price     : "s:call.for.price"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.CUSTOMER_PROFILE_PAGE)         : [

                    overview_top_selling_product   : "true",
                    overview_featured_product      : "true",
                    overview_onsale_product        : "true",
                    overview_new_product           : "true",
                    overview_last_viewed_product   : "true",
                    overview_last_bought_product   : "true",
                    max_top_selling_product        : "10",
                    max_featured_product           : "10",
                    max_onsale_product             : "10",
                    max_new_product                : "10",
                    max_last_viewed_product        : "10",
                    max_last_bought_product        : "10",
                    show_on_hover                  : 'false',
                    add_to_cart                    : 'true',
                    page_html                      : "",
                    welcome_message_order          : "1",
                    welcome_message_label          : "Welcome Message",
                    welcome_message_default_label  : "Welcome Message",
                    welcome_message_active         : "true",
                    overview_order                 : "2",
                    overview_label                 : "Overview",
                    overview_default_label         : "Overview",
                    overview_active                : "true",
                    manage_my_account_order        : "3",
                    manage_my_account_label        : "Manage My Account",
                    manage_my_account_default_label: "Manage My Account",
                    manage_my_account_active       : "true",
                    my_eorders_order               : "4",
                    my_eorders_label               : "My Orders",
                    my_eorders_default_label       : "My Orders",
                    my_eorders_active              : "true",
                    my_entitlements_order          : "5",
                    my_entitlements_label          : "My Entitlements",
                    my_entitlements_default_label  : "My Entitlements",
                    my_entitlements_active         : "true",
                    my_wallet_order                : "6",
                    my_wallet_label                : "My Wallet",
                    my_wallet_default_label        : "My Wallet",
                    my_wallet_active               : "true",
                    assigned_pages_order           : "7",
                    assigned_pages_label           : "Assigned Pages",
                    assigned_pages_default_label   : "Assigned Pages",
                    assigned_pages_active          : "true",
            ],
            (DomainConstants.SITE_CONFIG_TYPES.OVERVIEW)                      : [
                    overview_top_selling_product_active       : "true",
                    overview_top_selling_product_label        : "Top Selling Product",
                    overview_top_selling_product_default_label: "Top Selling Product",
                    overview_top_selling_product_order        : "1",
                    overview_featured_product_active          : "true",
                    overview_featured_product_label           : "Featured Product",
                    overview_featured_product_default_label   : "Featured Product",
                    overview_featured_product_order           : "2",
                    overview_onsale_product_active            : "true",
                    overview_onsale_product_label             : "On Sale Product",
                    overview_onsale_product_default_label     : "On Sale Product",
                    overview_onsale_product_order             : "3",
                    overview_new_product_active               : "true",
                    overview_new_product_label                : "New Product",
                    overview_new_product_default_label        : "New Product",
                    overview_new_product_order                : "4",
                    overview_last_viewed_product_active       : "true",
                    overview_last_viewed_product_label        : "Last Viewed Product",
                    overview_last_viewed_product_default_label: "Last Viewed Product",
                    overview_last_viewed_product_order        : "5",
                    overview_last_bought_product_active       : "true",
                    overview_last_bought_product_label        : "Last Bought Product",
                    overview_last_bought_product_default_label: "Last Bought Product",
                    overview_last_bought_product_order        : "6",
            ],
            (DomainConstants.SITE_CONFIG_TYPES.MANAGE_MY_ACCOUNT)             : [
                    account_information_order        : "1",
                    account_information_label        : "Account Information",
                    account_information_default_label: "Account Information",
                    account_information_active       : "true",
                    billing_address_order            : "2",
                    billing_address_label            : "Billing Address",
                    billing_address_default_label    : "Billing Address",
                    billing_address_active           : "true",
                    shipping_address_order           : "3",
                    shipping_address_label           : "Shipping Address",
                    shipping_address_default_label   : "Shipping Address",
                    shipping_address_active          : "true",
            ],
            (DomainConstants.SITE_CONFIG_TYPES.GET_STARTED_WIZARD)            : [
                    passed       : "true",
                    store_done   : "true",
                    email_done   : "true",
                    design_done  : "false",
                    product_done : "true",
                    page_done    : "true",
                    tax_done     : "true",
                    shipping_done: "true",
                    payment_done : "true",
                    launch_done  : "false"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.GET_STARTED_WIZARD)            : [
                    passed       : "true",
                    store_done   : "true",
                    email_done   : "true",
                    design_done  : "false",
                    product_done : "true",
                    page_done    : "true",
                    tax_done     : "true",
                    shipping_done: "true",
                    payment_done : "true",
                    launch_done  : "false"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.LICENSE)                       : [
                    licenseCode     : "",
                    licenseCache    : "",
                    package_name    : "",
                    package_weight  : "",
                    is_trial_package: ""
            ],
            (DomainConstants.SITE_CONFIG_TYPES.MANAGEMENT_HUB)                : [
                    instance_eight_digit: "",
                    instance_port       : ""
            ],
            (DomainConstants.SITE_CONFIG_TYPES.STORE_CREDIT)                  : [
                    apply_by_default: "true"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.PRODUCT_PROPERTIES)            : [
                    show_weight: "true",
                    show_length: "true",
                    show_width : "true",
                    show_height: "true"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.MY_ACCOUNT_PAGE)               : [
                    pending_order  : "false",
                    completed_order: "true",
                    assigned_page  : "true",
                    wallet         : "true",
                    store_credit   : "true"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.MY_ENTITLEMENTS)               : [

                    store_credit_active       : "true",
                    store_credit_label        : "My Store Credit",
                    store_credit_default_label: "My Store Credit",
                    store_credit_order        : "1",
            ],
            (DomainConstants.SITE_CONFIG_TYPES.MY_ORDERS)                     : [

                    pending_order_active         : "true",
                    pending_order_label          : "Pending Order",
                    pending_order_default_label  : "Pending Order",
                    pending_order_orderkey       : "1",
                    completed_order_active       : "true",
                    completed_order_label        : "Completed Order",
                    completed_order_default_label: "Completed Order",
                    completed_order_orderkey     : "2"
            ],
            (DomainConstants.SITE_CONFIG_TYPES.MY_CARTS)                      : [

            ],
            (DomainConstants.SITE_CONFIG_TYPES.MY_LISTS)                      : [

            ],(DomainConstants.SITE_CONFIG_TYPES.ELASTIC_SEARCH)              : [
                    url: "",
                    index: ""
            ],
    ]
}
