dataSource:
    host: localhost
    name: tab_accordion
    username: root
    password: ""

#server:
#  session:
#  timeout: 100

server:
    port: 9999

webcommander:
    provision:
        enabled: false

    multiTenant:
        enabled: false
        tenantResolverDataSource:
            server: mysql
            host: localhost
            name: wc_multi_tenant_resolver
            username: root
            password: ""