---
webcommander:
    servers:
        plugin: ''
        backup: ''
    provision:
        enabled: false
    sso:
        host: https://my.webcommander.com
        enabled: false
    version:
        number: '3.0.1'
        build: '000000-00000000'
        date: '0000-00-00'
    plugin:
        softInstallUnInstall: true
    multiTenant:
        enabled: false
        tenantResolverDataSource:
            server: mysql
            host: localhost
            name: wc_instance_lookup
            username: root
            password:
    wccp: http://localhost
    singleTenant:
        tenantId: "00000000"
    scheduler:
        tick: 600000 #10*60*1000
    cache:
        lifetime: 1
    adminpackages:
        - "com.webcommander.controllers.admin"
        - "com.webcommander.plugin.*.controllers.admin"
        - "com.webcommander.controllers.rest.admin"
        - "com.webcommander.plugin.*.controllers.rest.admin"

---
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

---
grails:
    profile: web
    codegen:
        defaultPackage: com.webcommander.starter
    gorm:
        reactor:
            events: false
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 3000000000000
            maxRequestSize: 300000000000
    converters:
        encoding: UTF-8
    views:
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: none
                scriptlets: none
                taglib: none
                staticparts: none
    resources:
        pattern: ['/**']
    server:
        hostname: localhost
        port:
            http: 80
            https: 443

endpoints:
    enabled: false
    jmx:
        enabled: true
        unique-names: true

---
hibernate:
    format_sql: true
    dialect: com.webcommander.hibernate.dialect.MySQLDialect
    cache:
        queries: true
        use_query_cache: true
        use_second_level_cache: true
        region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: false
    server: mysql
    host: localhost
    name: webcommander
    username: root
    password:
    dbCreate: update
    logSql: false

environments:
    development:
        dataSource:
            logSql: true
    production:
        dataSource:
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 100
                maxIdle: 5
                minIdle: 3
                maxWait: 100
                maxAge: 0
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 1200000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

logback:
    sql_log_params: false
    verbose: false