grails:
    views:
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: none
                scriptlets: none
                taglib: none
                staticparts: none